/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Timer;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author Jennifer Caballes
 */
public class gameplay extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
   
    BackgroundController bc = new BackgroundController();
    FuelController fc = new FuelController();
    ColliderController cc = new ColliderController();
    Thread th = new Thread(bc); 
    Thread th1 = new Thread(fc);
    Profile p = new Profile();
    ObstacleController ob = new ObstacleController();
    Thread th2 = new Thread(ob);
    Thread th3 = new Thread(cc);
    
    public gameplay() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(0);
        
        //set car 
        lbl_car.setIcon(new javax.swing.ImageIcon(getClass().getResource(p.carProfile)));
        
        
        //threads
       // fc.fuelCount(this);
        fc.FuelControllers(this);
        bc.MoveBackground(this);
        ob.setGp(this);
        boolean ret = cc.intersects(this.lbl_car, this.lbl_cone);
        th.start();
        th1.start();       
        th2.run();
        th3.start();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_left = new javax.swing.JButton();
        btn_up = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_down = new javax.swing.JButton();
        btn_right = new javax.swing.JButton();
        lbl_cone = new javax.swing.JLabel();
        lbl_spike1 = new javax.swing.JLabel();
        lbl_spike3 = new javax.swing.JLabel();
        lbl_spike2 = new javax.swing.JLabel();
        lbl_cone2 = new javax.swing.JLabel();
        lbl_cone3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_car = new javax.swing.JLabel();
        lbl_fuel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        btn_left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left.png"))); // NOI18N
        btn_left.setBorderPainted(false);
        btn_left.setContentAreaFilled(false);
        btn_left.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/right.png"))); // NOI18N
        btn_left.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_leftKeyPressed(evt);
            }
        });
        getContentPane().add(btn_left);
        btn_left.setBounds(140, 510, 70, 70);

        btn_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/up.png"))); // NOI18N
        btn_up.setBorderPainted(false);
        btn_up.setContentAreaFilled(false);
        btn_up.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/right.png"))); // NOI18N
        btn_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_upKeyPressed(evt);
            }
        });
        getContentPane().add(btn_up);
        btn_up.setBounds(200, 460, 50, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/whitelogo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 30, 310, 130);

        btn_down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/down.png"))); // NOI18N
        btn_down.setBorderPainted(false);
        btn_down.setContentAreaFilled(false);
        btn_down.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_downKeyPressed(evt);
            }
        });
        getContentPane().add(btn_down);
        btn_down.setBounds(200, 520, 50, 50);

        btn_right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/right.png"))); // NOI18N
        btn_right.setBorderPainted(false);
        btn_right.setContentAreaFilled(false);
        btn_right.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/right.png"))); // NOI18N
        btn_right.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_rightKeyPressed(evt);
            }
        });
        getContentPane().add(btn_right);
        btn_right.setBounds(250, 510, 50, 70);
        getContentPane().add(lbl_cone);
        lbl_cone.setBounds(480, 520, 30, 40);
        getContentPane().add(lbl_spike1);
        lbl_spike1.setBounds(600, 520, 30, 40);
        getContentPane().add(lbl_spike3);
        lbl_spike3.setBounds(440, 520, 30, 40);
        getContentPane().add(lbl_spike2);
        lbl_spike2.setBounds(560, 520, 30, 40);

        lbl_cone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cone2_top.png"))); // NOI18N
        getContentPane().add(lbl_cone2);
        lbl_cone2.setBounds(620, 860, 30, 40);
        getContentPane().add(lbl_cone3);
        lbl_cone3.setBounds(520, 520, 30, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TIRES.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 610, 150, 40);

        jLabel8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tires_used.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 590, 60, 70);

        jLabel11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tires_used.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 590, 60, 70);

        jLabel10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tires_used.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 590, 60, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FUELLBL.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 190, 210, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/CONTROLLERLBL.png"))); // NOI18N
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 400, 270, 50);

        lbl_car.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_carKeyPressed(evt);
            }
        });
        getContentPane().add(lbl_car);
        lbl_car.setBounds(710, 560, 70, 120);

        lbl_fuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fuelfull.png"))); // NOI18N
        lbl_fuel.setLabelFor(this);
        getContentPane().add(lbl_fuel);
        lbl_fuel.setBounds(110, 210, 210, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(967, 680));
        jLabel4.setMinimumSize(new java.awt.Dimension(967, 680));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -680, 2370, 680);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(967, 680));
        jLabel1.setMinimumSize(new java.awt.Dimension(967, 680));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 2370, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_upKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_upKeyPressed
                                        
                if(evt.getKeyCode() == KeyEvent.VK_DOWN && lbl_car.getY()<=540 )
                     {
                     lbl_car.setLocation(lbl_car.getX(),lbl_car.getY()+5);
                     repaint();
                 }
                 if(evt.getKeyCode() == KeyEvent.VK_UP && lbl_car.getY()>=3)
                     {
                     lbl_car.setLocation(lbl_car.getX(),lbl_car.getY()-5);
                     repaint();
                 }
                 if(evt.getKeyCode() == KeyEvent.VK_LEFT && lbl_car.getX()>= 670)
                     {
                     lbl_car.setLocation(lbl_car.getX()-5,lbl_car.getY());
                     repaint();
                 }
                 if(evt.getKeyCode() == KeyEvent.VK_RIGHT && lbl_car.getX()<=850)
                     {
                     lbl_car.setLocation(lbl_car.getX()+5,lbl_car.getY());
                     repaint();
                 }  
    }//GEN-LAST:event_btn_upKeyPressed

    private void btn_downKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_downKeyPressed

    }//GEN-LAST:event_btn_downKeyPressed

    private void lbl_carKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_carKeyPressed

    }//GEN-LAST:event_lbl_carKeyPressed

    private void btn_rightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_rightKeyPressed

    }//GEN-LAST:event_btn_rightKeyPressed

    private void btn_leftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_leftKeyPressed

    }//GEN-LAST:event_btn_leftKeyPressed

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed

    }//GEN-LAST:event_jLabel3KeyPressed
    
    public JButton getBtn_down() {
        return btn_down;
    }

    public void setBtn_down(JButton btn_down) {
        this.btn_down = btn_down;
    }

    public JButton getBtn_left() {
        return btn_left;
    }

    public void setBtn_left(JButton btn_left) {
        this.btn_left = btn_left;
    }

    public JButton getBtn_right() {
        return btn_right;
    }

    public void setBtn_right(JButton btn_right) {
        this.btn_right = btn_right;
    }

    public JButton getBtn_up() {
        return btn_up;
    }

    public void setBtn_up(JButton btn_up) {
        this.btn_up = btn_up;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

 
    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getLbl_car() {
        return lbl_car;
    }

    public void setLbl_car(JLabel lbl_car) {
        this.lbl_car = lbl_car;
    }

    public JLabel getLbl_fuel() {
        return lbl_fuel;
    }

    public void setLbl_fuel(JLabel lbl_fuel) {
        this.lbl_fuel = lbl_fuel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_down;
    private javax.swing.JButton btn_left;
    private javax.swing.JButton btn_right;
    private javax.swing.JButton btn_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_car;
    private javax.swing.JLabel lbl_cone;
    private javax.swing.JLabel lbl_cone2;
    private javax.swing.JLabel lbl_cone3;
    private javax.swing.JLabel lbl_fuel;
    private javax.swing.JLabel lbl_spike1;
    private javax.swing.JLabel lbl_spike2;
    private javax.swing.JLabel lbl_spike3;
    // End of variables declaration//GEN-END:variables

    
    public JLabel getLbl_cone() {
        return lbl_cone;
    }

    public void setLbl_cone(JLabel lbl_cone) {
        this.lbl_cone = lbl_cone;
    }

    public JLabel getLbl_cone2() {
        return lbl_cone2;
    }

    public void setLbl_cone2(JLabel lbl_cone2) {
        this.lbl_cone2 = lbl_cone2;
    }

    public JLabel getLbl_cone3() {
        return lbl_cone3;
    }

    public void setLbl_cone3(JLabel lbl_cone3) {
        this.lbl_cone3 = lbl_cone3;
    }

    public JLabel getLbl_spike1() {
        return lbl_spike1;
   }

    public void setLbl_spike1(JLabel lbl_spike1) {
        this.lbl_spike1 = lbl_spike1;
    }

    public JLabel getLbl_spike2() {
        return lbl_spike2;
    }

    public void setLbl_spike2(JLabel lbl_spike2) {
        this.lbl_spike2 = lbl_spike2;
    }

    public JLabel getLbl_spike3() {
        return lbl_spike3;
    }

    public void setLbl_spike3(JLabel lbl_spike3) {
        this.lbl_spike3 = lbl_spike3;
    }
}
